apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    App: NginxExample
  name: nginx-example
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      App: NginxExample
  template:
    metadata:
      labels:
        App: NginxExample
    spec:
      containers:
      - image: nginx:latest
        name: example
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 50Mi