apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16.2
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-data
          mountPath: /data/postgresql
        envFrom:
        - configMapRef:
            name: postgres-env
        - secretRef:
            name: postgres-secret
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      volumeMode: Filesystem
      storageClassName: standard
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10M
