apiVersion: v1
kind: Service
metadata:
  labels:
    App: embedder
  name: embedder-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 7997
  selector:
    App: embedder
  type: ClusterIP
